### PR TITLE
Add Create: Crafts & Additions compat

### PR DESCRIPTION
**Pull request by Dudblockman**
Adds crafting recipes for Crafts & Additions items

### CODE REVIEW

**Comment by logan-peterson** [comment]
Core integration recipes 
Rolling Mill = Andesite Machine + Shaft
Portable Energy Interface = Brass Machine (Stonecutter)
Tesla Coil = Brass Machine + Copper Spool
Accumulator = Brass Machine + Energy Cell Frame
Redstone Relay = Redstone component + Wire Connector


Small and Large Connectors changed to use sequenced assembly recipes, may need second opinions 
Small Connector = Andesite Alloy + Iron Plate + Copper Rod
Large Connector = Small Connector + Iron Plate + Molten Gold (1 nugget) 

Alternator & Electric Motor seem problematic for balance, my instinct is to remove them entirely, but I added recipes for them
Electric Motor = Invar Machine + Tesla Coil
Alternator = Enderium Machine + Electric Motor

**Comment by Dudblockman** [comment]
Main Recipes: 
Rolling Mill = Andesite Machine + Shaft
Portable Energy Interface = Andesite Machine
Tesla Coil = Brass Machine + Copper Spool
Accumulator = Brass Machine + Energy Cell Frame
Redstone Relay = Redstone Component + Connector

Small Connector and Large Connector were changed to be sequenced assembly. This may need further consideration.
Small Connector = Andesite Alloy + Iron Plate + Copper Rod
Large Conenctor = Small Connector + Iron Plate + Molten Gold

I don't think the electric motor and alternator themselves are a good fit for the pack even with tweaking the configs, added recipes for the sake of not making them uncraftable.
Electric Motor = Invar Machine + Tesla Coil
Alternator = Enderium Machine + Electric Motor

**Review by ThePansmith — COMMENTED** [review]
See about moving the C&A (and malum) bulk hiding to its own file for organizations sake. 
Good stuffs.

**Comment by cubebotfan** [comment]
> See about moving the C&A (and malum) bulk hiding to its own file for organizations sake. Good stuffs.
Updated. Now there are 3 compatability scripts for client, server and startup

**Pull request merged**
